//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintPaymentSystem_Demo.ServicePrintPayment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePrintPayment.IPrintPaymentService")]
    public interface IPrintPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/AddChfByCardId", ReplyAction="http://tempuri.org/IPrintPaymentService/AddChfByCardIdResponse")]
        void AddChfByCardId(int cardId, decimal chf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/AddChfByCardId", ReplyAction="http://tempuri.org/IPrintPaymentService/AddChfByCardIdResponse")]
        System.Threading.Tasks.Task AddChfByCardIdAsync(int cardId, decimal chf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/AddChfByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/AddChfByUsernameResponse")]
        void AddChfByUsername(string username, decimal chf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/AddChfByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/AddChfByUsernameResponse")]
        System.Threading.Tasks.Task AddChfByUsernameAsync(string username, decimal chf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/GetQuantityByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/GetQuantityByUsernameResponse")]
        decimal GetQuantityByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/GetQuantityByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/GetQuantityByUsernameResponse")]
        System.Threading.Tasks.Task<decimal> GetQuantityByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/GetChfByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/GetChfByUsernameResponse")]
        decimal GetChfByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/GetChfByUsername", ReplyAction="http://tempuri.org/IPrintPaymentService/GetChfByUsernameResponse")]
        System.Threading.Tasks.Task<decimal> GetChfByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintPaymentServiceChannel : PrintPaymentSystem_Demo.ServicePrintPayment.IPrintPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintPaymentServiceClient : System.ServiceModel.ClientBase<PrintPaymentSystem_Demo.ServicePrintPayment.IPrintPaymentService>, PrintPaymentSystem_Demo.ServicePrintPayment.IPrintPaymentService {
        
        public PrintPaymentServiceClient() {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddChfByCardId(int cardId, decimal chf) {
            base.Channel.AddChfByCardId(cardId, chf);
        }
        
        public System.Threading.Tasks.Task AddChfByCardIdAsync(int cardId, decimal chf) {
            return base.Channel.AddChfByCardIdAsync(cardId, chf);
        }
        
        public void AddChfByUsername(string username, decimal chf) {
            base.Channel.AddChfByUsername(username, chf);
        }
        
        public System.Threading.Tasks.Task AddChfByUsernameAsync(string username, decimal chf) {
            return base.Channel.AddChfByUsernameAsync(username, chf);
        }
        
        public decimal GetQuantityByUsername(string username) {
            return base.Channel.GetQuantityByUsername(username);
        }
        
        public System.Threading.Tasks.Task<decimal> GetQuantityByUsernameAsync(string username) {
            return base.Channel.GetQuantityByUsernameAsync(username);
        }
        
        public decimal GetChfByUsername(string username) {
            return base.Channel.GetChfByUsername(username);
        }
        
        public System.Threading.Tasks.Task<decimal> GetChfByUsernameAsync(string username) {
            return base.Channel.GetChfByUsernameAsync(username);
        }
    }
}
